@extends('site.layouts.front')

@section('title') {{ __('Политика конфеденциальности') }} @endsection

@section('breadcrumbs')
- {{ __('Политика конфеденциальности') }}
@endsection

@section('content')
<div class="title-top title-top--small">
	<h2>
		Политика конфеденциальности
	</h2>
</div>

<div class="px-4 py-4">

<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:18px;font-family:"Segoe UI",sans-serif;color:#212529;'>Пользовательское соглашение и политика конфиденциальности</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>Настоящая Политика конфиденциальности персональных данных (далее &ndash; Политика конфиденциальности) действует в отношении всей информации, которую сайт Itcase.com, (далее &ndash; Itcase.com) расположенный на доменном имени itcase.com (а также его субдоменах), может получить о Пользователе во время использования сайта-приложения itcase.com (а также его субдоменов), его программ и его продуктов.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:18px;font-family:"Segoe UI",sans-serif;color:#212529;'>1. Определение терминов</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1 В настоящей Политике конфиденциальности используются следующие термины:</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1.1. &laquo;Администрация сайта-приложения&raquo; (далее &ndash; Администрация) &ndash; уполномоченные сотрудники на управление сайтом Itcase.com, которые организуют и (или) осуществляют обработку персональных данных, а также определяет цели обработки персональных данных, состав персональных данных, подлежащих обработке, действия (операции), совершаемые с персональными данными.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1.2. &laquo;Персональные данные&raquo; - любая информация, относящаяся к прямо или косвенно определенному, или определяемому физическому лицу (субъекту персональных данных).</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1.3. &laquo;Обработка персональных данных&raquo; - любое действие (операция) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств с персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение персональных данных.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1.4. &laquo;Конфиденциальность персональных данных&raquo; - обязательное для соблюдения Оператором или иным получившим доступ к персональным данным лицом требование не допускать их распространения без согласия субъекта персональных данных или наличия иного законного основания.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1.5. &laquo;Сайт Itcase.com&raquo; - это совокупность связанных между собой веб-страниц, размещенных в сети Интернет по уникальному адресу (URL): itcase.com, а также его субдоменах.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1.6. &laquo;Субдомены&raquo; - это страницы или совокупность страниц, расположенные на доменах третьего уровня, принадлежащие сайту Itcase.com, а также другие временные страницы, внизу который указана контактная информация Администрации</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1.5. &laquo;Пользователь сайта-приложения-приложения&nbsp;</span><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>itcase</span><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>.</span><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>com</span><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>&nbsp;&raquo; (далее Пользователь) &ndash; лицо, имеющее доступ к сайту-приложению Itcase.com, посредством сети Интернет и использующее информацию, материалы и продукты сайта-приложения Itcase.com.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1.7. &laquo;Cookies&raquo; &mdash; небольшой фрагмент данных, отправленный веб-сервером и хранимый на компьютере пользователя, который веб-клиент или веб-браузер каждый раз пересылает веб-серверу в HTTP-запросе при попытке открыть страницу соответствующего сайта-приложения.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1.8. &laquo;IP-адрес&raquo; &mdash; уникальный сетевой адрес узла в компьютерной сети, через который Пользователь получает доступ на Itcase.com.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>1.1.9. &laquo;Камера&raquo; - фото для верификации пользователя и для отправки отчета о проделанной работе.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:18px;font-family:"Segoe UI",sans-serif;color:#212529;'>2. Общие положения</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>2.1. Использование сайта-приложения Itcase.com Пользователем означает согласие с настоящей Политикой конфиденциальности и условиями обработки персональных данных Пользователя.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>2.2. В случае несогласия с условиями Политики конфиденциальности Пользователь должен прекратить использование сайта-приложения Itcase.com .</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>2.3. Настоящая Политика конфиденциальности применяется к сайту Itcase.com. Itcase.com не контролирует и не несет ответственность за сайты третьих лиц, на которые Пользователь может перейти по ссылкам, доступным на сайте Itcase.com.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>2.4. Администрация не проверяет достоверность персональных данных, предоставляемых Пользователем.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:18px;font-family:"Segoe UI",sans-serif;color:#212529;'>3. Предмет политики конфиденциальности</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.1. Настоящая Политика конфиденциальности устанавливает обязательства Администрации по неразглашению и обеспечению режима защиты конфиденциальности персональных данных, которые Пользователь предоставляет по запросу Администрации при регистрации на сайте Itcase.com или при подписке на информационную e-mail рассылку.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.2. Персональные данные, разрешённые к обработке в рамках настоящей Политики конфиденциальности, предоставляются Пользователем путём заполнения форм на сайте Itcase.com и включают в себя следующую информацию:</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.2.1. фамилию, имя, отчество Пользователя;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.2.2. контактный телефон Пользователя;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.2.3. адрес электронной почты (e-mail)</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.2.4. место жительство Пользователя (при необходимости)</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.2.5. фотографию (при необходимости)</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.3. Itcase.com защищает Данные, которые автоматически передаются при посещении страниц:</span></p>
<ul style="margin-bottom:0in;" type="disc">
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#212529;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;'>- IP адрес;</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#212529;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;'>- информация из cookies;</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#212529;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;'>- информация о браузере</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#212529;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;'>- время доступа;</span></li>
    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;color:#212529;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;'>- реферер (адрес предыдущей страницы).</span></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.3.1. Отключение cookies может повлечь невозможность доступа к частям сайта-приложения , требующим авторизации.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.3.2. Itcase.com осуществляет сбор статистики об IP-адресах своих посетителей. Данная информация используется с целью предотвращения, выявления и решения технических проблем.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>3.4. Любая иная персональная информация неоговоренная выше (история посещения, используемые браузеры, операционные системы и т.д.) подлежит надежному хранению и нераспространению, за исключением случаев, предусмотренных в п.п. 5.2. настоящей Политики конфиденциальности.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:18px;font-family:"Segoe UI",sans-serif;color:#212529;'>4. Цели сбора персональной информации пользователя</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>4.1. Персональные данные Пользователя Администрация может использовать в целях:</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>4.1.1. Идентификации Пользователя, зарегистрированного на сайте Itcase.com для его дальнейшей авторизации.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>4.1.2. Предоставления Пользователю доступа к персонализированным данным сайта-приложения Itcase.com.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>4.1.3. Установления с Пользователем обратной связи, включая направление уведомлений, запросов, касающихся использования сайта-приложения Itcase.com, обработки запросов и заявок от Пользователя.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>4.1.4. Определения места нахождения Пользователя для обеспечения безопасности, предотвращения мошенничества.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>4.1.5. Подтверждения достоверности и полноты персональных данных, предоставленных Пользователем.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>4.1.6. Создания учетной записи для использования частей сайта-приложения Itcase.com, если Пользователь дал согласие на создание учетной записи.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>4.1.7. Уведомления Пользователя по электронной почте.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>4.1.8. Предоставления Пользователю эффективной технической поддержки при возникновении проблем, связанных с использованием сайта-приложения Itcase.com.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>4.1.9. Предоставления Пользователю с его согласия специальных предложений, новостной рассылки и иных сведений от имени сайта-приложения Itcase.com.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:18px;font-family:"Segoe UI",sans-serif;color:#212529;'>5. Способы и сроки обработки персональной информации</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>5.1. Обработка персональных данных Пользователя осуществляется без ограничения срока, любым законным способом, в том числе в информационных системах персональных данных с использованием средств автоматизации или без использования таких средств.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>5.2. Персональные данные Пользователя могут быть переданы уполномоченным органам государственной власти Российской Федерации только по основаниям и в порядке, установленным законодательством Республики Узбекистан.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>5.3. При утрате или разглашении персональных данных Администрация вправе не информировать Пользователя об утрате или разглашении персональных данных.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>5.4. Администрация принимает необходимые организационные и технические меры для защиты персональной информации Пользователя от неправомерного или случайного доступа, уничтожения, изменения, блокирования, копирования, распространения, а также от иных неправомерных действий третьих лиц.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>5.5. Администрация совместно с Пользователем принимает все необходимые меры по предотвращению убытков или иных отрицательных последствий, вызванных утратой или разглашением персональных данных Пользователя.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:18px;font-family:"Segoe UI",sans-serif;color:#212529;'>6. Права и обязанности сторон</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>6.1. Пользователь вправе:</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>6.1.1. Принимать свободное решение о предоставлении своих персональных данных, необходимых для использования сайта-приложения Itcase.com, и давать согласие на их обработку.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>6.1.2. Обновить, дополнить предоставленную информацию о персональных данных в случае изменения данной информации.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>6.1.3. Пользователь имеет право на получение у Администрации информации, касающейся обработки его персональных данных, если такое право не ограничено в соответствии с федеральными законами. Пользователь вправе требовать от Администрации уточнения его персональных данных, их блокирования или уничтожения в случае, если персональные данные являются неполными, устаревшими, неточными, незаконно полученными или не являются необходимыми для заявленной цели обработки, а также принимать предусмотренные законом меры по защите своих прав. Для этого достаточно уведомить Администрацию по указаному E-mail адресу.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>6.2. Администрация обязана:</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>6.2.1. Использовать полученную информацию исключительно для целей, указанных в п. 4 настоящей Политики конфиденциальности.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>6.2.2. Обеспечить хранение конфиденциальной информации в тайне, не разглашать без предварительного письменного разрешения Пользователя, а также не осуществлять продажу, обмен, опубликование, либо разглашение иными возможными способами переданных персональных данных Пользователя, за исключением п.п. 5.2. настоящей Политики Конфиденциальности.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>6.2.3. Принимать меры предосторожности для защиты конфиденциальности персональных данных Пользователя согласно порядку, обычно используемого для защиты такого рода информации в существующем деловом обороте.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>6.2.4. Осуществить блокирование персональных данных, относящихся к соответствующему Пользователю, с момента обращения или запроса Пользователя, или его законного представителя либо уполномоченного органа по защите прав субъектов персональных данных на период проверки, в случае выявления недостоверных персональных данных или неправомерных действий.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:18px;font-family:"Segoe UI",sans-serif;color:#212529;'>7 Ответственность сторон</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.1. Администрация, не исполнившая свои обязательства, несёт ответственность за убытки, понесённые Пользователем в связи с неправомерным использованием персональных данных, в соответствии с законодательством Республики Узбекистан, за исключением случаев, предусмотренных п.п. 5.2. и 7.2. настоящей Политики Конфиденциальности.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.2. В случае утраты или разглашения Конфиденциальной информации Администрация не несёт ответственность, если данная конфиденциальная информация:</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.2.1. Стала публичным достоянием до её утраты или разглашения.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.2.2. Была получена от третьей стороны до момента её получения Администрацией Ресурса.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.2.3. Была разглашена с согласия Пользователя.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.3. Пользователь несет полную ответственность за соблюдение требований законодательства РФ, в том числе законов о рекламе, о защите авторских и смежных прав, об охране товарных знаков и знаков обслуживания, но не ограничиваясь перечисленным, включая полную ответственность за содержание и форму материалов.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.4. Пользователь признает, что ответственность за любую информацию (в том числе, но не ограничиваясь: файлы с данными, тексты и т. д.), к которой он может иметь доступ как к части сайта-приложения Itcase.com, несет лицо, предоставившее такую информацию.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.5. Пользователь соглашается, что информация, предоставленная ему как часть сайта-приложения Itcase.com, может являться объектом интеллектуальной собственности, права на который защищены и принадлежат другим Пользователям, партнерам или рекламодателям, которые размещают такую информацию на сайте Itcase.com. Пользователь не вправе вносить изменения, передавать в аренду, передавать на условиях займа, продавать, распространять или создавать производные работы на основе такого Содержания (полностью или в части), за исключением случаев, когда такие действия были письменно прямо разрешены собственниками такого Содержания в соответствии с условиями отдельного соглашения.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.6. В отношение текстовых материалов (статей, публикаций, находящихся в свободном публичном доступе на сайте Itcase.com) допускается их распространение при условии, что будет дана ссылка на Itcase.com.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.7. Администрация не несет ответственности перед Пользователем за любой убыток или ущерб, понесенный Пользователем в результате удаления, сбоя или невозможности сохранения какого-либо Содержания и иных коммуникационных данных, содержащихся на сайте Itcase.com или передаваемых через него.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.8. Администрация не несет ответственности за любые прямые или косвенные убытки, произошедшие из-за: использования либо невозможности использования сайта-приложения, либо отдельных сервисов; несанкционированного доступа к коммуникациям Пользователя; заявления или поведение любого третьего лица на сайте.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>7.9. Администрация не несет ответственность за какую-либо информацию, размещенную пользователем на сайте Itcase.com, включая, но не ограничиваясь: информацию, защищенную авторским правом, без прямого согласия владельца авторского права.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:18px;font-family:"Segoe UI",sans-serif;color:#212529;'>8. Разрешение споров</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>8.1. До обращения в суд с иском по спорам, возникающим из отношений между Пользователем и Администрацией, обязательным является предъявление претензии (письменного предложения или предложения в электронном виде о добровольном урегулировании спора).</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>8.2. Получатель претензии в течение 30 календарных дней со дня получения претензии, письменно или в электронном виде уведомляет заявителя претензии о результатах рассмотрения претензии.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>8.3. При не достижении соглашения спор будет передан на рассмотрение Арбитражного суда г. Ташкент.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>8.4. К настоящей Политике конфиденциальности и отношениям между Пользователем и Администрацией применяется действующее законодательство Республики Узбекистан.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:18px;font-family:"Segoe UI",sans-serif;color:#212529;'>9. Дополнительные условия</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>9.1. Администрация вправе вносить изменения в настоящую Политику конфиденциальности без согласия Пользователя.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>9.2. Новая Политика конфиденциальности вступает в силу с момента ее размещения на сайте Itcase.com, если иное не предусмотрено новой редакцией Политики конфиденциальности.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>9.3. Все предложения или вопросы касательно настоящей Политики конфиденциальности следует сообщать по адресу: info@itcase.com</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;background:white;'><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>9.4. Действующая Политика конфиденциальности размещена на странице по адресу http://itcase.com/privacy-policy Обновлено: 11 Сентября 2019 года г. Ташкент, &quot;ООО&nbsp;</span><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>Avto</span><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>&nbsp;</span><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>Powerball</span><span style='font-size:16px;font-family:"Segoe UI",sans-serif;color:#212529;'>&quot;.</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>&nbsp;</p>

</div>

<div></div>
@endsection
