<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class TenderFile extends Model
{
    const UPLOAD_DIRECTORY = 'uploads/tenders/';

    protected $fillable = [
        'path'
    ];

    public function delete()
    {
        if ($this->path)
            Storage::delete(self::UPLOAD_DIRECTORY . $this->path);
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function getFileUrl()
    {
        if ($this->path)
            return '/' . self::UPLOAD_DIRECTORY . $this->path;
        return '';
    }
}
